# Explore here

In [1]:
# Your code here

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
main_df = pd.read_csv("https://breathecode.herokuapp.com/asset/internal-link?id=421&path=diabetes.csv")

main_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
train_df,test_df = train_test_split(main_df)

In [6]:
train_df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
173            1       79             60             42       48  43.5   
652            5      123             74             40       77  34.1   
730            3      130             78             23       79  28.4   
604            4      183              0              0        0  28.4   
478            8      126             74             38       75  25.9   
..           ...      ...            ...            ...      ...   ...   
469            6      154             78             41      140  46.1   
732            2      174             88             37      120  44.5   
75             1        0             48             20        0  24.7   
110            3      171             72             33      135  33.3   
603            7      150             78             29      126  35.2   

     DiabetesPedigreeFunction  Age  Outcome  
173                     0.678   23        0  
652                     0.269   28        0  
730                     0.323   34        1  
604                     0.212   36        1  
478                     0.162   39        0  
..                        ...  ...      ...  
469                     0.571   27        0  
732                     0.646   24        1  
75                      0.140   22        0  
110                     0.199   24        1  
603                     0.692   54        1  

[576 rows x 9 columns]

In [7]:
x_train = train_df.drop(columns=['Outcome'])
y_train = train_df['Outcome']

x_test = test_df.drop(columns=['Outcome'])
y_test = test_df['Outcome']

In [8]:
from sklearn.tree import DecisionTreeRegressor

In [9]:
df_model = DecisionTreeRegressor()
df_model.fit(x_train,y_train)

DecisionTreeRegressor()

In [10]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report

In [11]:
def model_evaluator(X_matrix, y_target, model):
    preds = model.predict(X_matrix)
    
    print(f"Accuracy score: {accuracy_score(y_true = y_target, y_pred = preds)}")
    print(f"Precision score: {precision_score(y_true = y_target, y_pred = preds)}")
    print(f"Recall score: {recall_score(y_true = y_target, y_pred = preds)}")
    print(f"Confusion matrix: \n{confusion_matrix(y_true = y_target, y_pred = preds)}")
    print(f"Classification report: \n{classification_report(y_true = y_target, y_pred = preds)}")

In [12]:
model_evaluator(x_train,y_train,df_model)

Accuracy score: 1.0
Precision score: 1.0
Recall score: 1.0
Confusion matrix: 
[[379   0]
 [  0 197]]
Classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       379
           1       1.00      1.00      1.00       197

    accuracy                           1.00       576
   macro avg       1.00      1.00      1.00       576
weighted avg       1.00      1.00      1.00       576



In [13]:
model_evaluator(x_test,y_test,df_model)

Accuracy score: 0.6927083333333334
Precision score: 0.603448275862069
Recall score: 0.49295774647887325
Confusion matrix: 
[[98 23]
 [36 35]]
Classification report: 
              precision    recall  f1-score   support

           0       0.73      0.81      0.77       121
           1       0.60      0.49      0.54        71

    accuracy                           0.69       192
   macro avg       0.67      0.65      0.66       192
weighted avg       0.68      0.69      0.69       192



In [14]:
df_model.get_depth

<bound method BaseDecisionTree.get_depth of DecisionTreeRegressor()>

In [15]:
from sklearn.tree import plot_tree

In [16]:
plt.figure(figsize=(100,100))
plot_tree(df_model);
plt.savefig

<function matplotlib.pyplot.savefig(*args, **kwargs) -> 'None'>

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
model = DecisionTreeClassifier()

In [19]:
hyperparameters_dict = {
    'criterion': ['gini', 'entropy', 'log_loss'],  # Liste kullan
    'max_depth': [2, 5, 10, 20],
    'min_samples_split': [2, 5, 10, 15, 25],
    'min_samples_leaf': [2, 5, 10, 2]}

In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
gridsearch_model = GridSearchCV(
    estimator=model,           # kullanmak istediğin model
    param_grid=hyperparameters_dict,  # denenecek parametreler
    scoring='accuracy',     # performans metriği
    cv=2                    # cross-validation kat sayısı
)


In [22]:
gridsearch_model.fit(x_train,y_train)

GridSearchCV(cv=2, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [2, 5, 10, 20],
                         'min_samples_leaf': [2, 5, 10, 2],
                         'min_samples_split': [2, 5, 10, 15, 25]},
             scoring='accuracy')

In [23]:
model_evaluator(x_train,y_train,gridsearch_model)

Accuracy score: 0.7708333333333334
Precision score: 0.7152317880794702
Recall score: 0.5482233502538071
Confusion matrix: 
[[336  43]
 [ 89 108]]
Classification report: 
              precision    recall  f1-score   support

           0       0.79      0.89      0.84       379
           1       0.72      0.55      0.62       197

    accuracy                           0.77       576
   macro avg       0.75      0.72      0.73       576
weighted avg       0.76      0.77      0.76       576



In [24]:
model_evaluator(x_test,y_test,gridsearch_model)

Accuracy score: 0.7760416666666666
Precision score: 0.75
Recall score: 0.5915492957746479
Confusion matrix: 
[[107  14]
 [ 29  42]]
Classification report: 
              precision    recall  f1-score   support

           0       0.79      0.88      0.83       121
           1       0.75      0.59      0.66        71

    accuracy                           0.78       192
   macro avg       0.77      0.74      0.75       192
weighted avg       0.77      0.78      0.77       192



In [25]:
gridsearch_model.best_params_

{'criterion': 'gini',
 'max_depth': 2,
 'min_samples_leaf': 2,
 'min_samples_split': 2}